export const SET_CONSTRUCTOR_ITEM = 'SET_CONSTRUCTOR_ITEM';
export const REMOVE_CONSTRUCTOR_ITEM = 'REMOVE_CONSTRUCTOR_ITEM';
export const REPLACE_CONSTRUCTOR_ITEMS = 'REPLACE_CONSTRUCTOR_ITEMS';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';