export const SET_CONSTRUCTOR_ITEM = 'SET_CONSTRUCTOR_ITEM' as const;
export const REMOVE_CONSTRUCTOR_ITEM = 'REMOVE_CONSTRUCTOR_ITEM' as const;
export const REPLACE_CONSTRUCTOR_ITEMS = 'REPLACE_CONSTRUCTOR_ITEMS' as const;
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR' as const;