export const GET_ORDER_NUMBER_REQUEST = 'GET_ORDER_NUMBER_REQUEST' as const;
export const GET_ORDER_NUMBER_SUCCESS = 'GET_ORDER_NUMBER_SUCCESS' as const;
export const GET_ORDER_NUMBER_ERROR = 'GET_ORDER_NUMBER_ERROR' as const;